version: "3"

services:
  langbot:
    image: rockchin/langbot:latest
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    restart: on-failure
    ports:
      - 5300:5300
    # 根据具体环境配置网络
