name: 漏洞反馈
description: 报错或漏洞请使用这个模板创建，不使用此模板创建的异常、漏洞相关issue将被直接关闭
title: "[Bug]: "
labels: ["bug?"]
body:
  - type: dropdown
    attributes:
      label: 消息平台适配器
      description: "连接QQ使用的框架"
      options:
        - yiri-mirai（Mirai）
        - Nakuru（go-cqhttp）
        - aiocqhttp（使用 OneBot 协议接入的）
        - qq-botpy（QQ官方API）
    validations:
      required: false
  - type: input
    attributes:
      label: 运行环境
      description: 操作系统、系统架构、**Python版本**、**主机地理位置**
      placeholder: 例如： CentOS x64 Python 3.10.3、Docker 的直接写 Docker 就行
    validations:
      required: true
  - type: input
    attributes:
      label: QChatGPT版本
      description: QChatGPT版本号
      placeholder: 例如：v3.3.0，可以使用`!version`命令查看，或者到 pkg/utils/constants.py 查看
    validations:
      required: true
  - type: textarea
    attributes:
      label: 异常情况
      description: 完整描述异常情况，什么时候发生的、发生了什么。**请附带日志信息。**
    validations:
      required: true
  - type: textarea
    attributes:
      label: 启用的插件
      description: 有些情况可能和插件功能有关，建议提供插件启用情况。可以使用`!plugin`命令查看已启用的插件
    validations:
      required: false
