name: trigger
label:
  en_US: Trigger
  zh_CN: 触发条件
stages:
  - name: group-respond-rules
    label:
      en_US: Group Respond Rule
      zh_CN: 群响应规则
    description:
      en_US: The group respond rule of the pipeline
      zh_CN: 群响应规则
    config:
      - name: at
        label:
          en_US: At
          zh_CN: '@'
        description:
          en_US: Whether to trigger when the message mentions the bot
          zh_CN: 是否在消息@机器人时触发
        type: boolean
        required: true
        default: false
      - name: prefix
        label:
          en_US: Prefix
          zh_CN: 前缀
        description:
          en_US: The prefix of the message
          zh_CN: 消息前缀
        type: array
        required: true
        default: []
        items:
          type: string
      - name: regexp
        label:
          en_US: Regexp
          zh_CN: 正则表达式
        description:
          en_US: The regexp of the message
          zh_CN: 消息正则表达式
        type: array
        required: true
        default: []
        items:
          type: string
      - name: random
        label:
          en_US: Random
          zh_CN: 随机
        description:
          en_US: The probability of the random response, range from 0.0 to 1.0
          zh_CN: 随机响应概率，范围为 0.0-1.0
        type: float
        required: false
        default: 0
  - name: access-control
    label:
      en_US: Access Control
      zh_CN: 访问控制
    config:
      - name: mode
        label:
          en_US: Mode
          zh_CN: 模式
        description:
          en_US: The mode of the access control
          zh_CN: 访问控制模式
        type: select
        required: true
        default: blacklist
        options:
          - name: blacklist
            label:
              en_US: Blacklist
              zh_CN: 黑名单
          - name: whitelist
            label:
              en_US: Whitelist
              zh_CN: 白名单
      - name: blacklist
        label:
          en_US: Blacklist
          zh_CN: 黑名单
        type: array
        required: true
        default: []
        items:
          type: string
      - name: whitelist
        label:
          en_US: Whitelist
          zh_CN: 白名单
        type: array
        required: true
        default: []
        items:
          type: string
  - name: ignore-rules
    label:
      en_US: Ignore Rules
      zh_CN: 消息忽略规则
    config:
      - name: prefix
        label:
          en_US: Prefix
          zh_CN: 前缀
        description:
          en_US: The prefix of the message
          zh_CN: 消息前缀
        type: array
        required: true
        default: []
        items:
          type: string
      - name: regexp
        label:
          en_US: Regexp
          zh_CN: 正则表达式
        description:
          en_US: The regexp of the message
          zh_CN: 消息正则表达式
        type: array
        required: true
        default: []
        items:
          type: string
