admins: []
api:
    port: 5300
command:
    prefix:
    - '!'
    - ！
    privilege: {}
concurrency:
    pipeline: 20
    session: 1
persistence:
    sqlite:
        path: data/langbot.db
proxy:
    http: ''
    https: ''
system:
    jwt:
        expire: 604800
        secret: bab3ba329e1fd7be096ac2c82f9b66f4
telemetry:
    report: true
    url: https://api.qchatgpt.rockchin.top/api/v2
